name: "\U0001F4A3 Security vulnerability"
description: "Create a report to help us improve"
labels: ['security']
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this security vulnerability report!"
  - type: textarea
    id: description
    attributes:
      label: "Describe the security vulnerability"
      description: "A clear and concise description of what the security vulnerability is. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or logs, screenshots etc. about the security vulnerability report here."
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: "Before submitting the issue, please make sure you do the following"
      options:
        - label: "Follow our [Code of Conduct](https://github.com/exotelis-labs/leafly-vue/blob/develop/.github/CODE_OF_CONDUCT.md)"
          required: true
        - label: "Read the docs"
          required: true
        - label: "Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate."
          required: true
