# This workflow will deploy the docs on GitHub pages when pushing to master

name: 'Deploy docs'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build'
        run: npm run docs:build
      - name: 'Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist